//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubiksCube.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CubeLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CubeLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RubiksCube.Resources.Languages.CubeLang", typeof(CubeLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to speech: Not all languages are supported that are provided in the application settings.
        ///This option varies from device to device and the installed languages. It is possible that for some languages the translation to and from speech is done over the internet by the concerned services.
        ///
        ///Google Translate was used for the translation of the text. This is not a guarantee that all translations are correct.
        ///The supporting languages are: Dutch, English, French, German, Italian, Portuguese and Spanish.
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutExplanation_Text {
            get {
                return ResourceManager.GetString("AboutExplanation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree_Text {
            get {
                return ResourceManager.GetString("Agree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed characters:.
        /// </summary>
        internal static string AllowedChar_Text {
            get {
                return ResourceManager.GetString("AllowedChar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed:.
        /// </summary>
        internal static string AllowedCharNot_Text {
            get {
                return ResourceManager.GetString("AllowedCharNot_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ButtonClose_Text {
            get {
                return ResourceManager.GetString("ButtonClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ButtonReset_Text {
            get {
                return ResourceManager.GetString("ButtonReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        internal static string ButtonSolve_Text {
            get {
                return ResourceManager.GetString("ButtonSolve_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the application..
        /// </summary>
        internal static string CloseApplication_Text {
            get {
                return ResourceManager.GetString("CloseApplication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string Contact_Text {
            get {
                return ResourceManager.GetString("Contact_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue_Text {
            get {
                return ResourceManager.GetString("Continue_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright_Text {
            get {
                return ResourceManager.GetString("Copyright_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string CubeBackSide_Text {
            get {
                return ResourceManager.GetString("CubeBackSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string CubeBottomSide_Text {
            get {
                return ResourceManager.GetString("CubeBottomSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube colors:.
        /// </summary>
        internal static string CubeColors_Text {
            get {
                return ResourceManager.GetString("CubeColors_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string CubeFrontSide_Text {
            get {
                return ResourceManager.GetString("CubeFrontSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate the cube sides &apos;clockwise&apos; and &apos;counter clockwise&apos;:
        ///If the command is given to turn the front &apos;clockwise&apos; then this is in the direction the hands are turning. &apos;Counter clockwise&apos; is turning in the other direction.
        ///For the other sides you always have to &apos;imagine&apos; that you are directly in front of the side to be turned. So if it says turn the back &apos;clockwise&apos; imagine you are on the other side of the cube and then turn the back &apos;clockwise&apos;. Do not rotate the cube itself..
        /// </summary>
        internal static string CubeHelp_Text {
            get {
                return ResourceManager.GetString("CubeHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside view.
        /// </summary>
        internal static string CubeInsideView_Text {
            get {
                return ResourceManager.GetString("CubeInsideView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string CubeLeftSide_Text {
            get {
                return ResourceManager.GetString("CubeLeftSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside view.
        /// </summary>
        internal static string CubeOutsideView_Text {
            get {
                return ResourceManager.GetString("CubeOutsideView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string CubeRightSide_Text {
            get {
                return ResourceManager.GetString("CubeRightSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string CubeTopSide_Text {
            get {
                return ResourceManager.GetString("CubeTopSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default_Text {
            get {
                return ResourceManager.GetString("Default_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or solve the cube..
        /// </summary>
        internal static string Description_Text {
            get {
                return ResourceManager.GetString("Description_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        internal static string Disagree_Text {
            get {
                return ResourceManager.GetString("Disagree_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        internal static string Email_Text {
            get {
                return ResourceManager.GetString("Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle_Text {
            get {
                return ResourceManager.GetString("ErrorTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explained by speech:.
        /// </summary>
        internal static string ExplainedBySpeech_Text {
            get {
                return ResourceManager.GetString("ExplainedBySpeech_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explained by text:.
        /// </summary>
        internal static string ExplainedByText_Text {
            get {
                return ResourceManager.GetString("ExplainedByText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal color codes:
        ///
        ///Characters 1-2: Red
        ///Characters 3-4: Green
        ///Characters 5-6: Blue.
        /// </summary>
        internal static string HexColorCodes_Text {
            get {
                return ResourceManager.GetString("HexColorCodes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_Text {
            get {
                return ResourceManager.GetString("Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language speech:.
        /// </summary>
        internal static string LanguageSpeech_Text {
            get {
                return ResourceManager.GetString("LanguageSpeech_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application may be used freely for non-commercial purposes.
        ///Use this program entirely at your own risk..
        /// </summary>
        internal static string License_Text {
            get {
                return ResourceManager.GetString("License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The software is provided &apos;as is&apos;, without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the author and/or publisher be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software..
        /// </summary>
        internal static string LicenseMit2_Text {
            get {
                return ResourceManager.GetString("LicenseMit2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string LicenseTitle_Text {
            get {
                return ResourceManager.GetString("LicenseTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the central square can only occur once..
        /// </summary>
        internal static string MessageColorCentralCube_Text {
            get {
                return ResourceManager.GetString("MessageColorCentralCube_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The colors of a corner cube must be different..
        /// </summary>
        internal static string MessageColorCornerCube_Text {
            get {
                return ResourceManager.GetString("MessageColorCornerCube_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The colors of an edge cube must be different..
        /// </summary>
        internal static string MessageColorEdgeCube_Text {
            get {
                return ResourceManager.GetString("MessageColorEdgeCube_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, the cube has been solved..
        /// </summary>
        internal static string MessageCubeIsSolved_Text {
            get {
                return ResourceManager.GetString("MessageCubeIsSolved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cube is not solved!.
        /// </summary>
        internal static string MessageCubeNotSolved_Text {
            get {
                return ResourceManager.GetString("MessageCubeNotSolved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of each available color, there must be nine of the same color!.
        /// </summary>
        internal static string MessageNineSameColor_Text {
            get {
                return ResourceManager.GetString("MessageNineSameColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubik&apos;s Cube.
        /// </summary>
        internal static string NameProgram_Text {
            get {
                return ResourceManager.GetString("NameProgram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No_Text {
            get {
                return ResourceManager.GetString("No_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No personal and other data is stored or passed on to myself and others..
        /// </summary>
        internal static string PrivacyPolicy_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy:.
        /// </summary>
        internal static string PrivacyPolicyTitle_Text {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will be restarted..
        /// </summary>
        internal static string RestartApp_Text {
            get {
                return ResourceManager.GetString("RestartApp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubik&apos;s Cube.
        /// </summary>
        internal static string RubiksCube_Text {
            get {
                return ResourceManager.GetString("RubiksCube_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Text {
            get {
                return ResourceManager.GetString("Settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SettingsReset_Text {
            get {
                return ResourceManager.GetString("SettingsReset_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SettingsSave_Text {
            get {
                return ResourceManager.GetString("SettingsSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changed settings must be saved in order to apply them.
        ///After saving, the application is restarted and the cube is reset..
        /// </summary>
        internal static string SettingsSaved_Text {
            get {
                return ResourceManager.GetString("SettingsSaved_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve.
        /// </summary>
        internal static string Solve_Text {
            get {
                return ResourceManager.GetString("Solve_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop_Text {
            get {
                return ResourceManager.GetString("Stop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text contains one or more characters that are not allowed.
        ///
        ///Not allowed:.
        /// </summary>
        internal static string TextContainsChar_Text {
            get {
                return ResourceManager.GetString("TextContainsChar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to speech is not supported on this device..
        /// </summary>
        internal static string TextToSpeechError_Text {
            get {
                return ResourceManager.GetString("TextToSpeechError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        internal static string Theme_Text {
            get {
                return ResourceManager.GetString("Theme_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark_Text {
            get {
                return ResourceManager.GetString("ThemeDark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight_Text {
            get {
                return ResourceManager.GetString("ThemeLight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ThemeSystem_Text {
            get {
                return ResourceManager.GetString("ThemeSystem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string ToolTipGoBack_Text {
            get {
                return ResourceManager.GetString("ToolTipGoBack_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go forward.
        /// </summary>
        internal static string ToolTipGoForward_Text {
            get {
                return ResourceManager.GetString("ToolTipGoForward_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the cube.
        /// </summary>
        internal static string ToolTipOpen_Text {
            get {
                return ResourceManager.GetString("ToolTipOpen_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the cube.
        /// </summary>
        internal static string ToolTipSave_Text {
            get {
                return ResourceManager.GetString("ToolTipSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle button: Drag the colors onto the cube.
        /// </summary>
        internal static string ToolTipSetColors_Text {
            get {
                return ResourceManager.GetString("ToolTipSetColors_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the back side half a turn..
        /// </summary>
        internal static string TurnBackSideHalfTurn_Text {
            get {
                return ResourceManager.GetString("TurnBackSideHalfTurn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the back side a quarter turn &apos;counter clockwise&apos; (-)..
        /// </summary>
        internal static string TurnBackSideToLeft_Text {
            get {
                return ResourceManager.GetString("TurnBackSideToLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the back side a quarter turn &apos;clockwise&apos; (+)..
        /// </summary>
        internal static string TurnBackSideToRight_Text {
            get {
                return ResourceManager.GetString("TurnBackSideToRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the bottom side half a turn..
        /// </summary>
        internal static string TurnBottomSideHalfTurn_Text {
            get {
                return ResourceManager.GetString("TurnBottomSideHalfTurn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the bottom side a quarter turn &apos;counter clockwise&apos; (-)..
        /// </summary>
        internal static string TurnBottomSideToLeft_Text {
            get {
                return ResourceManager.GetString("TurnBottomSideToLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the bottom side a quarter turn &apos;clockwise&apos; (+)..
        /// </summary>
        internal static string TurnBottomSideToRight_Text {
            get {
                return ResourceManager.GetString("TurnBottomSideToRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the entire cube so that the front goes to the bottom side..
        /// </summary>
        internal static string TurnCubeFrontSideToBottomSide_Text {
            get {
                return ResourceManager.GetString("TurnCubeFrontSideToBottomSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the entire cube so that the front goes to the left side..
        /// </summary>
        internal static string TurnCubeFrontSideToLeftSide_Text {
            get {
                return ResourceManager.GetString("TurnCubeFrontSideToLeftSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the entire cube so that the front goes to the right side..
        /// </summary>
        internal static string TurnCubeFrontSideToRightSide_Text {
            get {
                return ResourceManager.GetString("TurnCubeFrontSideToRightSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the entire cube so that the front goes to the top side..
        /// </summary>
        internal static string TurnCubeFrontSideToTopSide_Text {
            get {
                return ResourceManager.GetString("TurnCubeFrontSideToTopSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the entire cube so that the top goes to the left side..
        /// </summary>
        internal static string TurnCubeTopSideToLeftSide_Text {
            get {
                return ResourceManager.GetString("TurnCubeTopSideToLeftSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the entire cube so that the top goes to the right side..
        /// </summary>
        internal static string TurnCubeTopSideToRightSide_Text {
            get {
                return ResourceManager.GetString("TurnCubeTopSideToRightSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the front-middle layer a quarter turn to the right side (-)..
        /// </summary>
        internal static string TurnFrontMiddleToRightSide_Text {
            get {
                return ResourceManager.GetString("TurnFrontMiddleToRightSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the front-middle layer a quarter turn to the top side (+)..
        /// </summary>
        internal static string TurnFrontMiddleToTopSide_Text {
            get {
                return ResourceManager.GetString("TurnFrontMiddleToTopSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the front side half a turn..
        /// </summary>
        internal static string TurnFrontSideHalfTurn_Text {
            get {
                return ResourceManager.GetString("TurnFrontSideHalfTurn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the front side a quarter turn &apos;counter clockwise&apos; (-)..
        /// </summary>
        internal static string TurnFrontSideToLeft_Text {
            get {
                return ResourceManager.GetString("TurnFrontSideToLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the front side a quarter turn &apos;clockwise&apos; (+)..
        /// </summary>
        internal static string TurnFrontSideToRight_Text {
            get {
                return ResourceManager.GetString("TurnFrontSideToRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the left side half a turn..
        /// </summary>
        internal static string TurnLeftSideHalfTurn_Text {
            get {
                return ResourceManager.GetString("TurnLeftSideHalfTurn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the left side a quarter turn &apos;counter clockwise&apos; (-)..
        /// </summary>
        internal static string TurnLeftSideToLeft_Text {
            get {
                return ResourceManager.GetString("TurnLeftSideToLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the left side a quarter turn &apos;clockwise&apos; (+)..
        /// </summary>
        internal static string TurnLeftSideToRight_Text {
            get {
                return ResourceManager.GetString("TurnLeftSideToRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the right-middle layer a quarter turn to the front side (+)..
        /// </summary>
        internal static string TurnRightMiddleToFrontSide_Text {
            get {
                return ResourceManager.GetString("TurnRightMiddleToFrontSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the right-middle layer a quarter turn to the top side (-)..
        /// </summary>
        internal static string TurnRightMiddleToTopSide_Text {
            get {
                return ResourceManager.GetString("TurnRightMiddleToTopSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the right side half a turn..
        /// </summary>
        internal static string TurnRightSideHalfTurn_Text {
            get {
                return ResourceManager.GetString("TurnRightSideHalfTurn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the right side a quarter turn &apos;counter clockwise&apos; (-)..
        /// </summary>
        internal static string TurnRightSideToLeft_Text {
            get {
                return ResourceManager.GetString("TurnRightSideToLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the right side a quarter turn &apos;clockwise&apos; (+)..
        /// </summary>
        internal static string TurnRightSideToRight_Text {
            get {
                return ResourceManager.GetString("TurnRightSideToRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the top-middle layer a quarter turn to the front side (-)..
        /// </summary>
        internal static string TurnTopMiddleToFrontSide_Text {
            get {
                return ResourceManager.GetString("TurnTopMiddleToFrontSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the top-middle layer a quarter turn to the right side (+)..
        /// </summary>
        internal static string TurnTopMiddleToRightSide_Text {
            get {
                return ResourceManager.GetString("TurnTopMiddleToRightSide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the top side half a turn..
        /// </summary>
        internal static string TurnTopSideHalfTurn_Text {
            get {
                return ResourceManager.GetString("TurnTopSideHalfTurn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the top side a quarter turn &apos;counter clockwise&apos; (-)..
        /// </summary>
        internal static string TurnTopSideToLeft_Text {
            get {
                return ResourceManager.GetString("TurnTopSideToLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the top side a quarter turn &apos;clockwise&apos; (+)..
        /// </summary>
        internal static string TurnTopSideToRight_Text {
            get {
                return ResourceManager.GetString("TurnTopSideToRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version_Text {
            get {
                return ResourceManager.GetString("Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website_Text {
            get {
                return ResourceManager.GetString("Website_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes_Text {
            get {
                return ResourceManager.GetString("Yes_Text", resourceCulture);
            }
        }
    }
}
